spring.application.name=UrbanixApi-1



spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0&sslmode=require
spring.datasource.username=postgres.kmdoduuotpnwddhflehk
spring.datasource.password=dm@1nce2026$
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true